# Generated by Django 6.0.2 on 2026-03-04

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


def _forward_link_profiles(apps, schema_editor):
    UserAllergy = apps.get_model('allergy', 'UserAllergy')
    UserAllergyProfile = apps.get_model('allergy', 'UserAllergyProfile')

    user_ids = UserAllergy.objects.values_list('user_id', flat=True).distinct()
    for user_id in user_ids:
        UserAllergyProfile.objects.get_or_create(user_id=user_id)

    for allergy in UserAllergy.objects.all().iterator():
        profile, _ = UserAllergyProfile.objects.get_or_create(user_id=allergy.user_id)
        allergy.profile_id = profile.id
        allergy.save(update_fields=['profile'])


def _reverse_link_users(apps, schema_editor):
    UserAllergy = apps.get_model('allergy', 'UserAllergy')

    for allergy in UserAllergy.objects.select_related('profile').all().iterator():
        allergy.user_id = allergy.profile.user_id
        allergy.save(update_fields=['user'])


class Migration(migrations.Migration):

    dependencies = [
        ('allergy', '0002_userallergy_delete_allergyrecord'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAllergyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='allergy_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RenameField(
            model_name='userallergy',
            old_name='allergy_name',
            new_name='allergen_name',
        ),
        migrations.AddField(
            model_name='userallergy',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userallergy',
            name='item_type',
            field=models.CharField(choices=[('food', 'Food'), ('medicine', 'Medicine'), ('other', 'Other')], default='food', max_length=20),
        ),
        migrations.AddField(
            model_name='userallergy',
            name='notes',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userallergy',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='allergies', to='allergy.userallergyprofile'),
        ),
        migrations.AddField(
            model_name='userallergy',
            name='severity',
            field=models.CharField(choices=[('mild', 'Mild'), ('moderate', 'Moderate'), ('severe', 'Severe'), ('anaphylaxis', 'Anaphylaxis')], default='mild', max_length=20),
        ),
        migrations.AddField(
            model_name='userallergy',
            name='symptoms',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.RunPython(_forward_link_profiles, _reverse_link_users),
        migrations.RemoveField(
            model_name='userallergy',
            name='user',
        ),
        migrations.AlterField(
            model_name='userallergy',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allergies', to='allergy.userallergyprofile'),
        ),
        migrations.AlterModelOptions(
            name='userallergy',
            options={'ordering': ['-severity', 'allergen_name']},
        ),
        migrations.CreateModel(
            name='PredictionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=300)),
                ('item_type', models.CharField(default='food', max_length=20)),
                ('ingredients_text', models.TextField()),
                ('risk_level', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=10)),
                ('confidence', models.FloatField()),
                ('allergens_found', models.JSONField(default=list)),
                ('matched_allergens', models.JSONField(default=list)),
                ('alternatives', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
