# Generated by Django 6.0.2 on 2026-03-04 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allergy', '0003_sync_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userallergy',
            name='allergen_name',
            field=models.CharField(max_length=200),
        ),
    ]
